Set content type from content when tagging (#4)
### Checklist

* [x] I have read the [Contributor Guide](../../CONTRIBUTING.md)
* [x] I have read and agree to the [Code of
Conduct](../../CODE_OF_CONDUCT.md)
* [x] I have added a description of my changes and why I'd like them
included in the section below

### Description of Changes

When tagging I get the following error
```
Error: {"errors":[{"code":"MANIFEST_INVALID","message":"manifest has invalid format"}]}
```

Turns out the content receive from the get request is
`application/vnd.docker.distribution.manifest.v2+json`, but it seems the
content may have a bunch of different content types (see
https://docs.docker.com/registry/spec/api/#pulling-an-image-manifest),
so this pr changes to setting it to whatever is returned from the get
request.